name = "MLFlowLogger"
uuid = "a17d1b34-d2df-4d9e-9e11-6289e57bd259"
authors = ["rejuvyesh <mail@rejuvyesh.com> and contributors"]
version = "0.3.3"

[deps]
MLFlowClient = "64a0f543-368b-4a9a-827a-e71edb2a0b83"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
