name = "MLFlowLogger"
uuid = "a17d1b34-d2df-4d9e-9e11-6289e57bd259"
authors = ["rejuvyesh <mail@rejuvyesh.com> and contributors"]
version = "0.2.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
julia = "1.5"
PyCall = "1.0, 2.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
